#!/bin/bash

die() { echo "$*" 1>&2 ; exit 1; }

start_time=$(date +%s%3N)  # start time in milliseconds

dbusr=pmdb_rw
dbpwd=readwrite
dbnam=pm

files=(/home/m/dev/purple_martians/logs/net/*.csv)   # Put all filenames in array $files

[ -e "$files" ] || die "No files found."             # Exit if no files found

for file in "${files[@]}";do                         # foreach file:

mysql -u $dbusr -p$dbpwd $dbnam -vv --local_infile=1 -e"LOAD DATA LOCAL INFILE '$file' INTO TABLE logs COLUMNS TERMINATED BY ',' LINES TERMINATED BY '\n' (msg_type, sub_type, created, agt, frame_num, player, client, message);"

mv $file $file.bak

done

end_time=$(date +%s%3N)  # # end time in milliseconds
duration_ms=$((end_time - start_time))  # duration in milliseconds

echo "Execution time in ms: $duration_ms"












